### ISSUE TITLE
[Feature Request] Allow editing of task title immediately after it's created.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SolarLune/masterplan#10]
Right now, you create a new task. I expected to start typing but I have to click the empty box and edit it from there.

**Comment by SolarLune** [comment]
Hello! I saw this earlier and was thinking maybe I missed something, but that's the way it works right now. The description box is highlighted by default when creating new Tasks. Unless you mean that the task doesn't open for editing right after creation? 

If so, I'm not sure quite if that's a good idea; you might want to position the Task after creation before editing it.

**Comment by ThinkDigitalSoftware** [comment]
I would personally expect that the task isn't considered created until after it has at least a title or description. And that's the first thing I wanna do

**Comment by SolarLune** [comment]
A blank Task can exist; there's nothing that says it _has_ to have that information to exist first, but I do think it should be consistent (double-clicking a Task creates and opens it for editing), so I'll make it consistent and have new tasks open immediately.
