### ISSUE TITLE
Progression Tasks

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SolarLune/masterplan#12]
Hope I'm not nitpicking :D 
<img width="474" alt="Screen Shot 2020-02-02 at 12 20 17 PM" src="https://user-images.githubusercontent.com/23037821/73614760-dcdc2200-45b6-11ea-9d15-dac6e2d7e1b2.png">
Box `#2` should always be higher than box `#1`, right? Maybe they can be tied together so that `#2` increases if `#1` does? IDK

**Comment by SolarLune** [comment]
Fixed this in the referenced commit. Thanks!
