### ISSUE TITLE
Notifications Flash at Full Opacity Before Disappearing

### ISSUE THREAD

**Issue by BiRD4** [SolarLune/masterplan#14]
Notifications sometimes flash right before they disappear. I can't figure out a pattern that might indicate the reason, though.

Windows 10 64-bit
master branch (commit 4e60a82), Build: windows_amd64

**Comment by SolarLune** [comment]
Hello! Thanks for the report and sorry for not seeing it until today; this has been fixed, I believe, In the commits since your report. Try updating to the latest commit and rebuilding, or waiting until I push out a new build for v0.2.0 today (probably).
