### ISSUE TITLE
[Proposal] Move task options to top of menu

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SolarLune/masterplan#15]
<img width="294" alt="Screen Shot 2020-03-10 at 12 17 47 PM" src="https://user-images.githubusercontent.com/23037821/76350532-2d871f00-62c9-11ea-883b-1d48e5f39324.png">
I would like to propose moving task related options higher up the menu since I believe more frequently used than creating new projects, etc. Just a small suggestion

**Comment by SolarLune** [comment]
Yo! I could move them up in the menu, but I don't know if that's necessary as currently, the right click menu opens with the mouse centered on the New Task option (so Task options are "closer" by design).

**Comment by ThinkDigitalSoftware** [comment]
Just from a UX perspective, my eyes still travel to the topmost item first. I didn't notice that it was highlighted until you mention it. Up to you. Just some feedback :)

On Mar 10, 2020 12:47 PM, SolarLune <notifications@github.com> wrote:

Yo! I could move them up in the menu, but I don't know if that's necessary as currently, the right click menu opens with the mouse centered on the New Task option (so Task options are "closer" by design).

**Comment by SolarLune** [comment]
Hello!

It's been awhile, and I appreciate this report. I think I'll leave it the way it is for now, as I believe that's a good general flow for a menu - Project > Tasks > Misc. feels OK. If other people mention it, though, I'll return to this topic and reconsider. Thanks, again, for your feedback!
