### ISSUE TITLE
[Feature Request] Store settings in a different path

### ISSUE THREAD

**Issue by kforney** [SolarLune/masterplan#18]
On Linux, MasterPlan's settings are stored in ~/settings.json, a file directly in the user's home directory.  Not only does this file name not express which application created it, but since it's in a path used by other applications, it would be easy for something else to casually overwrite or write other data into this file.

If possible, this file should probably go in ~/.config/masterplan/settings.json instead, to give it a path unique to MasterPlan.

**Comment by Lachee** [comment]
Shouldn't settings be relative to the masterplan executable?

**Comment by kforney** [comment]
That would be ideal, yes.  Since you said that, though, I did a bit of further testing.

If run through itch.io's launcher, or directly from within the directory where the executable is located, it creates the settings.json file in the masterplan directory.  However, if run from anywhere else, it creates the settings.json file in the current working directory.  If run through a launcher in the menu of a desktop environment, the current working directory happens to be the home directory, so MasterPlan's settings.json file gets created there.  

That's how I initially noticed this behavior: I didn't want to launch MasterPlan through itch, so I made a shortcut to it in my menu, and then noticed that settings.json wound up in my home directory, which was unexpected.

**Comment by Lachee** [comment]
hmm, working directory is kinda the expected behavior. Maybe it should be changed to find the directory master plan is in and put itself there. Additionally, probably rename it to `masterplan-settings.json` to avoid accidental conflicts?

**Comment by SolarLune** [comment]
Whoops, this should always be MasterPlan's main directory. I'll change things around~

**Comment by theogen-ratkin** [comment]
Pull request #40 makes use of [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), so the config would go to `~/.config/MasterPlan/settings.json`, like @kforney originally suggested.
