### ISSUE TITLE
Autoload Last Plan Setting Forgotten on Restart

### ISSUE THREAD

**Issue by BiRD4** [SolarLune/masterplan#19]
If the "Auto-load Last Saved Project" option is checked in the project settings, the settings.json file updates with the correct information, but when MasterPlan restarts, it doesn't auto-load the last plan, and the setting in the project settings is unchecked.

Windows 10 64-bit
master branch (commit 40f188c), Build: windows_amd64

**Comment by SolarLune** [comment]
Yo! I believe this should be fixed in the latest commit. Let me know if it's not.

**Comment by BiRD4** [comment]
👍 Looks good :)
