### ISSUE TITLE
Window resize issue on macOS 

### ISSUE THREAD

**Issue by Zooce** [SolarLune/masterplan#2]
**Description:**
On macOS, resizing the window presents a rendering issue where the view is constrained to the bottom right corner of the window. After that, moving the resized window zooms into the view covering up the task bar at the bottom.

**System Info:**
macOS 10.15.2
MasterPlan 0.1.0

**Steps to Reproduce:**
1. Start MaserPlan on macOS 10.15.2
<img width="1072" alt="MasterPlan_resize_issue_0" src="https://user-images.githubusercontent.com/5490155/72404699-8005ee00-3713-11ea-8218-3dff7147640c.png">
2. Resize the window:
<img width="1357" alt="MasterPlan_resize_issue_1" src="https://user-images.githubusercontent.com/5490155/72404634-3c12e900-3713-11ea-88dc-2c5487deeec4.png">
3. Move the window:
<img width="1065" alt="MasterPlan_resize_issue_2" src="https://user-images.githubusercontent.com/5490155/72404656-52b94000-3713-11ea-832b-c1f9bf7f5fce.png">

**Comment by tawdry-audrey** [comment]
I can confirm I'm having the same issue, plus something that may be related which is that tasks go invisible when they're not in the top left corner of the screen and the right click menu seems to be offset similarly (i have to click a few options below my selection to click a selection)

**Comment by ThinkDigitalSoftware** [comment]
Same issue as well.

**Comment by Zooce** [comment]
@tawdry-audrey I think you're onto something with the top left corner thing. I mentioned it in #4.

**Comment by Zooce** [comment]
This issue seems to be fixed with 0.1.1 (somewhere between 720200d and f76b441). Thank you @SolarLune.
