### ISSUE TITLE
Numbering Sequence Appears Set to "Off" on Boards 1+ on Project Load

### ISSUE THREAD

**Issue by BiRD4** [SolarLune/masterplan#20]
If MasterPlan loads a file with a numbering sequence set, board 0 correctly displays the numbering sequence on the tasks, but the other boards appear to have the numbering sequence set to "Off." When the right-click menu is opened and closed, this fixes the currently displayed board, and when a task is set to be the focused task, this also fixes it, unless the task was focused because of cutting/copying and pasting, in which case, some weird stuff can happen:
![image](https://user-images.githubusercontent.com/20910668/76539627-63f2a480-6457-11ea-9a5b-95bffdba84c6.png)

Windows 10 64-bit
master branch (commit 40f188c), Build: windows_amd64

**Comment by SolarLune** [comment]
Yo! This should be fixed in the next commit. Thanks for reporting; I think it was due to me forgetting to restrict Task neighbors to just the same Board.

**Comment by BiRD4** [comment]
Unfortunately, I don't think this fixed it.
Before reopening:
![image](https://user-images.githubusercontent.com/20910668/76639009-cb762600-6523-11ea-8c50-c775eb50763d.png)
After reopening:
![image](https://user-images.githubusercontent.com/20910668/76638991-c1542780-6523-11ea-8526-cff2947e43e9.png)

Windows 10 64-bit
master branch (commit 41d0022), Build: windows_amd64

**Comment by BiRD4** [comment]
Also, if it helps, it seems that when I do something to fix the task numbers, like opening and closing the right-click menu, it only fixes the ones that are on-screen.

**Comment by SolarLune** [comment]
Whoops, I misunderstood what the issue was and fixed a related bug. I'll reopen and then commit the fix.
