### ISSUE TITLE
Can't Use Down Arrow Key to Move when Topmost Task in Board is Focused

### ISSUE THREAD

**Issue by BiRD4** [SolarLune/masterplan#21]
When the topmost task in the board is the focused task, the down arrow key doesn't work to move to the next task down.
![image](https://user-images.githubusercontent.com/20910668/76638389-be0c6c00-6522-11ea-9833-08d50f47c967.png)

Windows 10 64-bit
master branch (commit 41d0022), Build: windows_amd64

**Comment by SolarLune** [comment]
Whoops, I fixed this. Thanks for the report!
