### ISSUE TITLE
No support for Russian

### ISSUE THREAD

**Issue by EvolutionPixG** [SolarLune/masterplan#22]
If you write in Russian, there is nothing(instead of text, just empty characters).

![2020 05 17](https://user-images.githubusercontent.com/12032252/82148374-75439d00-985c-11ea-9cf3-4f74cd0654f2.png)

**Comment by SolarLune** [comment]
Hello, I responded to this on the forums - many languages are, by definition, not supported at the moment. I have to resolve this by adding fonts for those languages. This will probably be when I get to language support, which is a bit of a ways away. Thanks for the issue, though - I'll close this for now.
