### ISSUE TITLE
Dependency resolution issue

### ISSUE THREAD

**Issue by ryanhartje** [SolarLune/masterplan#23]
Hi,

I'm interested in this project, however when I checked it out and went to resolve dependencies, `go mod` failed with:

```
go mod download
go: github.com/gen2brain/raylib-go@v0.0.0-20191004100518-02424e2e10ea: parsing ../raylib-go-solarlune/go.mod: open /Users/ryan/go/src/github.com/solarlune/raylib-go-solarlune/go.mod: no such file or directory
```

I'm using `go version go1.14.2 darwin/amd64`

I also tried using the suggest build script, but go mod itself is failing with this each time:
```
go run build_script/main.go -b
go: github.com/gen2brain/raylib-go@v0.0.0-20191004100518-02424e2e10ea: parsing ../raylib-go-solarlune/go.mod: open /Users/ryan/go/src/github.com/solarlune/raylib-go-solarlune/go.mod: no such file or directory
```

The root of the issue is the go mod patch to use your custom libraries. Maybe you've recently archived github.com/solarlune/raylib-go-solarlune ?

**Comment by ryanhartje** [comment]
I can confirm that this project doesn't work with the upstream raylib bindings, for what it's worth. I removed the replace in `go.mod` and got:
```
 run main.go
# github.com/gen2brain/raylib-go/raylib
In file included from ../../../../pkg/mod/github.com/gen2brain/raylib-go@v0.0.0-20191004100518-02424e2e10ea/raylib/cgo_darwin.go:17:
../../../../pkg/mod/github.com/gen2brain/raylib-go@v0.0.0-20191004100518-02424e2e10ea/raylib/external/glfw/src/cocoa_window.m:1117:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
# command-line-arguments
./main.go:14:21: undefined: Project
./main.go:37:33: undefined: GetPath
./main.go:41:23: undefined: GetPath
./main.go:41:60: cannot use nil as type int32 in argument to rl.LoadFontEx
./main.go:41:77: cannot use 256 (type int) as type *int32 in argument to rl.LoadFontEx
./main.go:42:26: undefined: GetPath
./main.go:42:63: cannot use nil as type int32 in argument to rl.LoadFontEx
./main.go:42:83: cannot use 256 (type int) as type *int32 in argument to rl.LoadFontEx
./main.go:44:2: undefined: programSettings
./main.go:46:19: undefined: NewProject
./main.go:46:19: too many errors
```

**Comment by SolarLune** [comment]
Hello! Sorry for the late reply; I missed this somehow.

I didn't archive the repo, it was on my profile. The documentation on readme.md mentioned that you needed to manually check out that repo and place it next to MasterPlan's source folder before building; I believe that was the missing step that precluded you from building properly previously.

In any case, I've updated MasterPlan to use the latest raylib-go bindings, as well as my repo of raylib, and MasterPlan's readme with easier build instructions. 

Now you should just be able to run `go run ./` to get MP to run, or run the build script to build. It should automatically resolve to my repo without you needing to checkout a local copy first.

**Comment by SolarLune** [comment]
Let me know if it works for you and I'll close the issue.

**Comment by ryanhartje** [comment]
It does indeed.

**Comment by SolarLune** [comment]
Excellent, glad to hear it. Thanks!
