### ISSUE TITLE
[Feature Request] Change save dialogue on windows

### ISSUE THREAD

**Issue by joleeee** [SolarLune/masterplan#24]
I understand you use linux but a lot of us primarily use windows and then this dialogue is quite annoying because you cannot type in a path or select one of your 'pinned' locations.
![bilde](https://user-images.githubusercontent.com/24441708/83915841-573ecd80-a774-11ea-90a2-37460edfc677.png)
Excuse the non english screenshots, but i hope they still get the point across.

It is *supposed* to look something like this:
![bilde](https://user-images.githubusercontent.com/24441708/83916144-f794f200-a774-11ea-8763-b7de488a8818.png)

This is of course my personal preference. I will look into making a PR later but I'm not fluent in golang.

**Comment by Lachee** [comment]
This maybe a limitation of windows. Directory Dialog vs File Dialog.

**Comment by SolarLune** [comment]
Hello!

So yes, it would be ideal for the save dialogue to be a standard "File Save" dialog, but spawning dialogs in a cross-platform manner isn't something MasterPlan does itself. It uses gen2brain's [dlgs](https://github.com/gen2brain/dlgs) repo to handle this. 

dlgs does not have the ability to spawn a file save dialog, unfortunately. Spending time to research, write, and test that functionality for all major three OSes just for a relatively minor QoL improvement isn't especially high priority for me at the moment. The current functionality is basically the closest I could get with the tools I found at the time that I was building the project save and loading code.

However, I did see that sqweek's [dialog](https://github.com/sqweek/dialog) library exists, which might be sufficient for MasterPlan's needs. I'll see if I can make use of it (or other alternatives) to spawn file save dialogs cross-platform and move from specifying project folders.

**Comment by muevoid** [comment]
Couldnt you also implement a file dialog in raygui similar to the custom_file_dialog example?

**Comment by SolarLune** [comment]
Hello, sorry for the late reply; this actually isn't be a problem anymore, as I switched to using zenity to spawn dialogs. It calls up the correct file save dialog that includes the favorite locations at the side and search option at the top, as requested. I'll close this now. Thank you very much!
