### ISSUE TITLE
Mouse Tracking issue on MacOS

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SolarLune/masterplan#4]
![2020-01-15 19 24 28](https://user-images.githubusercontent.com/23037821/72490656-b6537400-37cc-11ea-8d82-bc2cdf71e08a.gif)

**Comment by Zooce** [comment]
Something possibly related to this and #2 is that I can't seem to get the context menu unless I'm in the top left corner. Additionally, after I create a task in the top left quadrant, moving the canvas view too high upwards makes the task disappear -- it reappears if the move the canvas view back down.

**Create the task:**
<img width="1072" alt="MasterPlan_task_render_issue_1" src="https://user-images.githubusercontent.com/5490155/72495181-308ef300-37e3-11ea-8631-18cd5fff9d3f.png">

**Move canvas view up:**
Notice I still have 0/1 tasks complete.
<img width="1072" alt="MasterPlan_task_render_issue_2" src="https://user-images.githubusercontent.com/5490155/72495202-3d134b80-37e3-11ea-8670-c64ee2152c0f.png">

**Comment by SolarLune** [comment]
Hello! 

Thanks for the examples and reports - I'm going to guess this has to do with high-res Retina displays.

I'd like to ask if you could try turning on [low resolution mode for the app](https://support.apple.com/en-us/HT202471) - if that works, then I'll probably just see about building that into the application somehow.

**Comment by ThinkDigitalSoftware** [comment]
Thanks for your response. Unfortunately this isn't available for this app. It may have to do with the fact that it's compiled into a binary instead of a .app package


On Jan 17, 2020 11:41 AM, SolarLune <notifications@github.com> wrote:

Hello!

Thanks for the examples and reports - I'm going to guess this has to do with high-res Retina displays.

I'd like to ask if you could try turning on low resolution mode for the app<https://support.apple.com/en-us/HT202471> - if that works, then I'll probably just see about building that into the application somehow.

**Comment by ThinkDigitalSoftware** [comment]
Thanks for your response. Unfortunately,
 this isn't available for this app. It may have to do with the fact that it's compiled into a binary instead of a .app package
<img width="377" alt="Screen Shot 2020-01-17 at 12 31 29 PM" src="https://user-images.githubusercontent.com/23037821/72644442-e3676a00-3925-11ea-80b9-f1fb52c70dcb.png">

**Comment by SolarLune** [comment]
That might be the case; I am just finishing up making it into a .app file - not sure if that will give the option, though, as my Mac doesn't have Retina support, so I can't test if it would make a difference. I'll see if it does, though, when I push an update later today.

**Comment by tawdry-audrey** [comment]
This problem was fixed for me following the update, thanks!

**Comment by SolarLune** [comment]
Excellent to hear! Thanks; I'll close this, then.
