### ISSUE TITLE
WMClass tied to version in Linux

### ISSUE THREAD

**Issue by Neyvermore** [SolarLune/masterplan#41]
Hi,

I've bought Masterplan on Linux, so I need to create a desktop file. However, without StartupWMClass in the .desktop, this is what happens : 
![photo_2020-11-20_10-36-54](https://user-images.githubusercontent.com/15616862/99793642-3d7a2280-2b29-11eb-83bd-3b3a8a1816b2.jpg)

What should happen is this : 
![photo_2020-11-20_10-36-03](https://user-images.githubusercontent.com/15616862/99793682-4e2a9880-2b29-11eb-9c0c-ebd2da74ab0a.jpg)

For that, I had to use the `xprop | grep WM_CLASS` command, which gave me this output : `WM_CLASS(STRING) = "MasterPlan v0.6.0", "MasterPlan v0.6.0`

The issue here is that I need to add `StartupWMClass=Masterplan v0.6.0.` to my .desktop file, which means that as soon as I upgrade to i.e. 0.7.0, I'll have to manually change this line. A simple fix would be to change the WM_CLASS to `Masterplan`, I guess?

**Comment by SolarLune** [comment]
Yo, it looks like this is set when initializing the window. A fix for this was just pushed (simply setting the title to "MasterPlan" initially, and then changing the title later for version number, open plan file, etc), so WM_CLASS should just be "MasterPlan" now.
