### ISSUE TITLE
Multiple simultaneous plans

### ISSUE THREAD

**Issue by MaliusArth** [SolarLune/masterplan#43]
win 10:
trying to open a different plan while another plan is already open creates a second window with the previous (first) plan instead of the opened (second) plan.

apparently the behavior is that opening a .plan file from file explorer just starts masterplan, which simply loads the last open plan, instead of opening the .plan file with masterplan

my expected behavior would be that when i open .plan files from file explorer each of these .plan files is opened in separate windows, resulting in multiple different plans open at the same time for multi-tasking purposes (eventually with the ability to also copy tasks from one plan to another etc.)

**Comment by SolarLune** [comment]
Hello, sorry for the late reply~

To make things clear, you're referring to when you double-click on a .plan file, that MasterPlan opens the previously opened plan on Windows? This is not proper behavior; I'll investigate it.

**Comment by SolarLune** [comment]
Hello, again. I've fixed this in today's commit (https://github.com/SolarLune/masterplan/commit/955b1b7e38b85d4b833efc885f51c33a140aa42d). Now when you double-click a plan, it should open properly.
