### ISSUE TITLE
Disable mouse smoothing

### ISSUE THREAD

**Issue by Neyvermore** [SolarLune/masterplan#44]
Hello,

The keyboard controls are great, however, when dragging the screen using the mouse wheel, there's an annoying smoothing. An option to disable with be great ! (I've searched and haven't found anything related to it in the issues. Please, forgive me if there is one already)

I'm using the Linux version built from the git repo, if that's helpful.

Thanks again for such a great program !

**Comment by SolarLune** [comment]
Hello! Sorry for the late reply; I missed this feature request. 

I'll see about adding an option to disable mouse smoothing for panning in the settings. 

Thank you!

**Comment by SolarLune** [comment]
Hello~ this option is available in the latest version of MasterPlan. Thank you for the suggestion!
