### ISSUE TITLE
Masterplan Versions 4 & 5 Wont Launch On Win10

### ISSUE THREAD

**Issue by Theory-of-Everything** [SolarLune/masterplan#46]
So I have a bit of an odd issue, but an issue nonetheless.
When I have Masterplan Versions 4 OR 5 installed on my system, when launched, nothing happens.
Oddly Enough, when I install an older version of masterplan (In this case Ver. 3) the software works perfectly fine as it should.
Another note is that masterplan isn't instaled in the itch launcher defal directory, as I have use a custom one. (I don't think that this is an issue but I though I might as well point it out)

A Bit More Details of my system hardware:
CPU: Intel i7 8700 8th gen
GPU: Nvidia GTX 1060 6gb 
RAM: 16GB Two stick kit

**Comment by Theory-of-Everything** [comment]
I also forgot to mention that nothing appears in the log files.

**Comment by SolarLune** [comment]
Hmm, strange. There was an issue that caused crashes shortly after launching, but that has been patched and pushed out. 

MasterPlan runs fine for me on a Windows 10 Acer Switch - are you sure you've updated MasterPlan fully? It should show as v0.6.1-1 in the window titlebar. If you are running the latest version of MasterPlan, it should now have settings and a log file in C:\Users\<Your Username>\AppData\Local\MasterPlan.

**Comment by Theory-of-Everything** [comment]
Sorry it took me awhile. I just updated Masterplan to Version 5 (the latest on the itch launcher) 
and now it works.... somehow. 

Originally I could not run ver 5, but for whatever reason, it decided to work now. So sorry if this issue was sorta redundant.

**Comment by SolarLune** [comment]
No, no problem.

I think it might have just been that the app didn't update fully the first time you tried it, or maybe updates are checked regularly rather than on demand, I'm not sure.

In any case, glad it's resolved.
