### ISSUE TITLE
Bug: task "overdue by" value skips a day

### ISSUE THREAD

**Issue by sir-pinecone** [SolarLune/masterplan#51]
I'm seeing the following behaviour when setting a deadline on a task:

Current day = 17th
Deadline = 16th -> Overdue by 1 day
**Deadline = 15th -> Overdue by 2 days**
**Deadline = 14th -> Overdue by 2 days**
Deadline = 13th -> Overdue by 3 days
...

This might be related to the timer issue I logged in #50.

**Comment by SolarLune** [comment]
Hello, thank you very much for your bug report.

The last commit should've resolved this issue; both this one and the other one (#50) were caused by incorrect internal date handling around daylight savings time changes. Thanks a lot for the report, again!

Regards~
