### ISSUE TITLE
NixOS packaging

### ISSUE THREAD

**Issue by critbase** [SolarLune/masterplan#55]
hey, i like your software and i use nixos so i wrote a package for it. i'm not sure if getting it into the main nix repos would count as redistributing builds, so would you mind if i made a pr adding the package expression to this repo? (though i'm not sure how many other nixos users are also using this software)

**Comment by SolarLune** [comment]
Hello! Thanks a lot for using MasterPlan; I appreciate it! Yes, getting it into the repos would count as redistribution, so I appreciate you not adding it in there.

Making a PR for this could be nice, but I feel like it's not a large enough need to outweight the added cost. Would it be possible to simply post the necessary files here, or is packaging for NixOS more complicated? I'm unfamiliar with the distro.

**Comment by critbase** [comment]
> Would it be possible to simply post the necessary files here, or is packaging for NixOS more complicated? I'm unfamiliar with the distro.

Yeah, no problem. If anything, NixOS makes it easy to install arbitrary packages that aren't in the main repos.

For any fellow NixOS users: just make sure these two files are in the same directory, then you should be able to build masterplan with `nix-build -E "with import <nixpkgs> {}; callPackage ./default.nix"`
[default.nix](https://github.com/SolarLune/masterplan/files/6371046/default.nix.txt)
[deps.nix](https://github.com/SolarLune/masterplan/files/6371047/deps.nix.txt)

**Comment by SolarLune** [comment]
God it. Thanks a lot! I'll close this issue, but any NixOS users can refer to this to build it easily.
