### ISSUE TITLE
[Feature Request] Pasting images directly in

### ISSUE THREAD

**Issue by ben-watt-es** [SolarLune/masterplan#59]
You can drag images in, and you can copy text into a note or task.
But I can't see a way of copying an image in. "Paste Content" just says "unable to create task from clipboard content" if I have an image in there.

**Comment by SolarLune** [comment]
Hello, thanks for the request - the next version in the sdl-rework branch will support this and the feature has already been added as of the following commit: https://github.com/SolarLune/masterplan/commit/9fb4346619528fcf4fcce296bc0040a6e2048176. I'll close this for now. Thanks!
