### ISSUE TITLE
Incorrect colors when creating custom theme

### ISSUE THREAD

**Issue by bcaccia** [SolarLune/masterplan#6]
**Environment:**
* Masterplan v0.1.1(compiled from master branch)
* Kubuntu 18.04
* i3wm 4.14.1

**Repro:**
1. Duplicate an existing theme in `/masterplan/bin/linux_amd64/assets/themes` and rename it. I called mine `Gruvbox_dark.json`
2. Change the `GUI_INSIDE` property in the json file to an obvious color such as `204, 36, 29, 1`
3. Save the changes, launch Masterplan, and load your theme.

**Expected:**
The background will be the following color:
![image](https://user-images.githubusercontent.com/23156454/72685462-4852c980-3ab8-11ea-8379-4602d21e1d04.png)

**Bug:**

The background is black:
![image](https://user-images.githubusercontent.com/23156454/72685492-b4353200-3ab8-11ea-881f-3bcb41f9776d.png)

If I change every value in the `Gruvbox_dark.json` file to that red, the whole UI is completely black.
To rule out that just that color was an issue, I tested with several other colors from the Gruvbox palette located here: https://github.com/morhetz/gruvbox

**Comment by SolarLune** [comment]
The alpha argument is 1, which is basically invisible. The format is RGBA, and each value spans from 0 to 255 max.

**Comment by bcaccia** [comment]
Thanks, total user error. Confirmed this works correctly when the value is set to 255. This can be closed.

**Comment by SolarLune** [comment]
OK, cool, just wanted to be sure. Thanks!
