### ISSUE TITLE
Can`t drag and drop images

### ISSUE THREAD

**Issue by Phern4ndo** [SolarLune/masterplan#62]
Using drag and drop with images in v0.8 crash masteplan without notice.

**Comment by SolarLune** [comment]
Hello, I just saw this - I believe this should be resolved if you're on Windows and dragging and dropping .jpegs, specifically. Is that the case?

**Comment by Phern4ndo** [comment]
For me, in windows 10 and windows 11, it only works with .png files.

**Comment by SolarLune** [comment]
This is strange - is this on v0.8-alpha 2? Or Alpha 1?
What does the log file say? It can be found in %LOCALAPPDATA%\MasterPlan (also known as C:\Users\(your username)\AppData\Local\MasterPlan).

**Comment by Phern4ndo** [comment]
My bad, issue was related to the old build Alpha 1. 

Thanks for your time!
