### ISSUE TITLE
[Feedback?] Select animation is too rapid

### ISSUE THREAD

**Issue by SaphireLattice** [SolarLune/masterplan#63]
Hi! Absolutely loved this from the screenshots and decided to give it a spin

But uh, in motion it looks almost dizzying. There's issue with the background rippling around due to being uniform pattern scaled to far down, which is separate issue...

But the primary mode of interacting with tasks, where you need to select it, rapidly makes me want to avoid selecting tasks more than necessary just from the sheer rapid blinking of the animation that surrounds the selected task. I have not found an option to turn it off? I do like there being a highlight around the selected task, but I really really would prefer not to have the rapid blinking.

Edit: Ah, found the option, `Settings > Tasks > Pulse Selected Tasks` which still does not disable pulsing darkening of the task. That one is `Selected Tasks Glow`, but counterintuitively it changes them to be the same color as not-selected tasks, which with a 1px-per-1px zoom causes it to be near impossible to see the thin blue selection border.

**Comment by SolarLune** [comment]
Hello, thanks for your feedback! I've since overhauled MasterPlan from the ground up, rebuilding it from scratch with SDL2. The selection animation pulsing and being too rapid is no longer is a problem, so I'll close this issue now. Thank you, again!
