### ISSUE TITLE
Instant Snap to Origin Before Panning Animation on Snap to Origin

### ISSUE THREAD

**Issue by BiRD4** [SolarLune/masterplan#7]
When the backspace key is pressed for snap to origin, the view teleports directly to the origin for a frame or two before doing the panning animation. Tasks located near the origin only appear in these couple frames if they were already loaded on-screen before the backspace key is pressed for the snap to origin, so it's possible that whatever code is responsible for drawing only the tasks that are in the view doesn't think the view is at the origin for these frames.

Build: windows_amd64
On Windows 10 64-bit

**Comment by SolarLune** [comment]
Fixed by the most recent commit; will be in the next build on itch if you don't build (v0.1.2).
