### ISSUE TITLE
[Feature Request] Calendar?

### ISSUE THREAD

**Issue by skejeton** [SolarLune/masterplan#74]
A calendar would be nice, It's similar to a checkbox, where you can pick a date that you need to check before the due, if you don't check it before the due date it's colored red (you can still check/uncheck it after due date anyway). Just throwing some ideas into the box, no pressure :)

**Comment by SolarLune** [comment]
Hello! I ended up implementing a calendar for due dates, so I'll close this issue. Thank you very much for the suggestion!
