### ISSUE TITLE
[Documentation] Include 'Card: Disconnect All Arrows'

### ISSUE THREAD

**Issue by kovitikus** [SolarLune/masterplan#78]
https://github.com/SolarLune/masterplan/wiki/Cards#connections

The very first sentence explains that connections can be created using the `Z` keybinding. The subsequent sentence should explain that using `SHIFT + Z`, while having cards selected, will remove all connections from those cards.

**Comment by SolarLune** [comment]
Hello! This has been documented now - thank you very much for your suggestion! I'll close this now.
