### ISSUE TITLE
[Suggestion] Checkbox appearance after removing all text

### ISSUE THREAD

**Issue by mvsrgc** [SolarLune/masterplan#80]
When you create a checkbox and add text that makes it so that the checkbox creates a newline, and then you delete all text in the checkbox, the checkbox keeps its "newline appearance" instead of reverting back to it's default appearance.

Default look:
![image](https://user-images.githubusercontent.com/14826113/174445405-5a3bf6af-c9a0-4eeb-ab14-455068229869.png)

After adding newline:
![image](https://user-images.githubusercontent.com/14826113/174445425-687df921-6f22-4a41-9bab-e2a24bc4a6a7.png)

After removing all text:
![image](https://user-images.githubusercontent.com/14826113/174445454-b656297a-205a-4a47-8218-a7e070527d62.png)

I think it would be more appropriate for the checkbox to return to it's default look when all text in it is deleted.

**Comment by SolarLune** [comment]
Hello! I just implemented this feature in this (kinda chonky) commit for all cards (not just checkboxes): https://github.com/SolarLune/masterplan/commit/8b6e8f370f09b2530eb1279fd584f56254e1b12a

So, I'll close this now. Thank you very much for the feature suggestion!
