### ISSUE TITLE
Encounter HTML Output no longer has 300px fixed width

### ISSUE THREAD

**Issue by Ingwion** [SolarLune/masterplan#82]
It would be useful to put the 300px fixed width back in to the current version, this resolves well for printing and display. Currently the output is set to 99% and fills a full browser window.

**Comment by SolarLune** [comment]
I'm sorry, I'm not sure what you mean - MasterPlan isn't available on browsers?

**Comment by Ingwion** [comment]
I'm sorry I wasn't very precise. This is the output from an encounter that is written to a HTML file.

![image](https://user-images.githubusercontent.com/108992001/178151796-94780c27-63da-4b9d-9e02-e0ec250d1cf9.png)

**Comment by SolarLune** [comment]
OK, yeah, this is a different program, lol

I'm the creator of MasterPlan. You're using Masterplan, hahahaha

But yeah, in truth, my repo is for a project planning software for game development. It looks like you're looking for this repo: https://github.com/andyaiken/masterplan, which is a DnD campaign planning tool, right?

**Comment by Ingwion** [comment]
Oops terribly sorry!
