### ISSUE TITLE
Prevent context menu from displaying off screen

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SolarLune/masterplan#9]
![2020-02-02 12 04 11](https://user-images.githubusercontent.com/23037821/73614473-3abb3a80-45b4-11ea-98b2-9c1b531a2f11.gif)
Currently, it's impossible to access certain menu items if you click too close to the borders.

**Comment by SolarLune** [comment]
Hello! That is indeed a bug; it should be fixed in the referenced commit. You can build yourself, or wait for the itch build coming through today (v0.1.2). Thanks!
